version: '3'

services:
  resume-writer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped 